schema_version = 1
id = "N0002"
title = "Feature Proposal: Vault Export Migration Tool"
created = "2026-04-09T15:42:12.809642700Z"
updated = "2026-04-09T16:21:04.039740700Z"
tags = []
links = ["N0018"]
sources = []
status = "draft"
