schema_version = 1
id = "N0018"
title = "v0.3 Discussion Notes"
created = "2026-04-09T16:19:03.734910300Z"
updated = "2026-04-09T17:14:44.204200500Z"
tags = [
    "decision",
    "proposal",
]
links = [
    "N0002",
    "N0004",
    "N0013",
    "N0019",
]
sources = []
status = "draft"
