schema_version = 1
id = "N0001"
title = "Elendirna Project Overview"
created = "2026-04-09T15:38:13.585892200Z"
updated = "2026-04-10T06:45:23.466957900Z"
tags = []
links = []
sources = []
status = "draft"
