schema_version = 1
id = "N0029"
title = "Elendirna: Problem Statement and Positioning"
created = "2026-04-13T08:53:25.837431700Z"
updated = "2026-04-13T08:53:44.542104900Z"
tags = [
    "core",
    "philosophy",
]
links = []
sources = []
status = "draft"
