schema_version = 1
id = "N0007"
title = "Elendirna Project Overview"
created = "2026-04-09T10:39:58.848138600Z"
updated = "2026-04-09T10:40:10.696268600Z"
tags = [
    "elendirna",
    "concept",
]
links = []
sources = []
status = "draft"
